# Generated by Django 5.2.15 on 2026-06-22 06:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventStore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('aggregate_id', models.CharField(max_length=64)),
                ('tenant_id', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('schema_version', models.IntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'event_store',
                'indexes': [models.Index(fields=['aggregate_id', 'id'], name='event_store_aggrega_367715_idx'), models.Index(fields=['tenant_id', 'id'], name='event_store_tenant__2fb160_idx')],
            },
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(unique=True)),
                ('topic', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=64)),
                ('envelope', models.JSONField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_outbox',
                'indexes': [models.Index(condition=models.Q(('published_at__isnull', True)), fields=['id'], name='outbox_unpublished_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('consumer_group', models.CharField(max_length=100)),
                ('event_id', models.UUIDField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_processed',
                'constraints': [models.UniqueConstraint(fields=('consumer_group', 'event_id'), name='uq_processed_group_event')],
            },
        ),
    ]
