# Generated by Django 5.2.15 on 2026-06-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalation',
            name='trigger_type',
            field=models.CharField(choices=[('ai', 'AI'), ('visitor', 'Visitor'), ('agent', 'Agent')], max_length=10),
        ),
    ]
