# Generated by Django 5.2.15 on 2026-06-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField()),
                ('call_type', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('input_tokens', models.BigIntegerField(default=0)),
                ('output_tokens', models.BigIntegerField(default=0)),
                ('total_tokens', models.BigIntegerField(default=0)),
                ('request_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'token_usage',
                'indexes': [models.Index(fields=['tenant_id', 'date'], name='token_usage_tenant__125247_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'call_type', 'model', 'date'), name='token_usage_unique_bucket')],
            },
        ),
    ]
