# Generated by Django 5.2.15 on 2026-06-23 05:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=63, null=True, unique=True)),
                ('tenant_key_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'operators',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TenantAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_agents',
                'unique_together': {('tenant', 'username')},
            },
        ),
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(default='openrouter/owl-alpha', max_length=255)),
                ('llm_provider_type', models.CharField(blank=True, default='', max_length=20)),
                ('llm_base_url', models.CharField(blank=True, default='', max_length=500)),
                ('llm_api_key', models.TextField(blank=True, default='')),
                ('extraction_model', models.CharField(blank=True, default='', max_length=255)),
                ('embed_provider_type', models.CharField(blank=True, default='', max_length=20)),
                ('embed_base_url', models.CharField(blank=True, default='', max_length=500)),
                ('embed_api_key', models.TextField(blank=True, default='')),
                ('embed_model', models.CharField(blank=True, default='', max_length=255)),
                ('embed_dim', models.IntegerField(default=1024)),
                ('ocr_provider_type', models.CharField(blank=True, default='', max_length=20)),
                ('ocr_base_url', models.CharField(blank=True, default='', max_length=500)),
                ('ocr_api_key', models.TextField(blank=True, default='')),
                ('ocr_model', models.CharField(blank=True, default='', max_length=255)),
                ('system_prompt', models.TextField(default='You are a helpful assistant. Answer questions clearly and concisely.')),
                ('agent_display_name', models.CharField(default='상담원', max_length=100)),
                ('webhook_url', models.URLField(blank=True, default='')),
                ('webhook_type', models.CharField(blank=True, choices=[('slack', 'Slack'), ('discord', 'Discord'), ('generic', 'Generic')], default='', max_length=10)),
                ('welcome_message', models.TextField(blank=True, default='')),
                ('brand_name', models.CharField(blank=True, default='', max_length=100)),
                ('require_identity_verification', models.BooleanField(default=False)),
                ('hitl_enabled', models.BooleanField(default=True)),
                ('hitl_timezone', models.CharField(blank=True, default='', max_length=64)),
                ('hitl_schedule', models.JSONField(blank=True, default=dict)),
                ('hitl_holidays', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_configs',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family_id', models.UUIDField(db_index=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('family_expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
                ('tenant_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='tenants.tenantagent')),
            ],
            options={
                'db_table': 'refresh_tokens',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('operator__isnull', False), ('tenant_agent__isnull', True)), models.Q(('operator__isnull', True), ('tenant_agent__isnull', False)), _connector='OR'), name='refresh_exactly_one_subject')],
            },
        ),
    ]
