# Generated by Django 5.2.15 on 2026-06-19 01:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_tenantconfig_embedding_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family_id', models.UUIDField(db_index=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('family_expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
                ('tenant_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='tenants.tenantagent')),
            ],
            options={
                'db_table': 'refresh_tokens',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('operator__isnull', False), ('tenant_agent__isnull', True)), models.Q(('operator__isnull', True), ('tenant_agent__isnull', False)), _connector='OR'), name='refresh_exactly_one_subject')],
            },
        ),
    ]
