# Generated by Django 5.2.15 on 2026-06-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='hitl_holidays',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='hitl_schedule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='hitl_timezone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
