# Generated by Django 5.2.15 on 2026-06-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_tenantconfig_hitl_holidays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='ocr_api_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='ocr_base_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='ocr_model',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='ocr_provider_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
