# Generated by Django 5.2.15 on 2026-06-16 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_is_hitl'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='chat_sessio_tenant__f3ac56_idx',
            old_name='chat_sess_tenant_visitor_idx',
        ),
    ]
