# Generated by Django 5.2.15 on 2026-06-23 05:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('source_type', models.CharField(default='file', max_length=10)),
                ('source_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents',
                'indexes': [models.Index(fields=['tenant_id'], name='documents_tenant__ad8c7d_idx')],
            },
        ),
    ]
