# Generated by Django 5.2.15 on 2026-06-16 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_alter_embedding_dimensions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_tenant__ad8c7d_idx',
            old_name='doc_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='document_ch_tenant__e81b7a_idx',
            old_name='chunk_tenant_idx',
        ),
    ]
