# Generated by Django 5.2.15 on 2026-06-23 05:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField()),
                ('visitor_id', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'visitor_memories',
                'indexes': [models.Index(fields=['tenant_id', 'visitor_id'], name='visitor_mem_tenant__75ff43_idx')],
                'unique_together': {('tenant_id', 'visitor_id', 'key')},
            },
        ),
    ]
