# Generated by Django 5.2.15 on 2026-06-16 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='visitormemory',
            new_name='visitor_mem_tenant__75ff43_idx',
            old_name='mem_tenant_visitor_idx',
        ),
    ]
